// src/app/models/modifiers.constants.ts

export const RACES = [
  'Anão',
  'Elfo',
  'Humano',
  'Goblin',
  'Lefou',
  'Hynne',
  'Qareen',
  'Minauro',
  'Kliren',
  'Medusa',
  'Sílfide',
  'Tritão',
];

export const CLASSES = [
  'Arcanista',
  'Bárbaro',
  'Druida',
  'Bucaneiro',
  'Caçador',
  'Cavaleiro',
  'Clérigo',
  'Guerreiro',
  'Inventor',
  'Ladino',
  'Lutador',
  'Nobre',
  'Paladino',
  'Ranger',
  'Samurai',
  'Templário',
  'InventorArcano',
];

export const RACE_MODIFIERS: Record<string, Record<string, number>> = {
  Anão: {
    strength: 2,
    dexterity: -1,
    constitution: 2,
    intelligence: 0,
    wisdom: 1,
    charisma: -2,
  },
  Elfo: {
    strength: -1,
    dexterity: 2,
    constitution: -1,
    intelligence: 2,
    wisdom: 1,
    charisma: 0,
  },
  Humano: {
    strength: 0,
    dexterity: 0,
    constitution: 0,
    intelligence: 0,
    wisdom: 0,
    charisma: 0,
  },
  Goblin: {
    strength: -2,
    dexterity: 2,
    constitution: -1,
    intelligence: 1,
    wisdom: 0,
    charisma: 0,
  },
  Lefou: {
    strength: 0,
    dexterity: 0,
    constitution: 0,
    intelligence: 0,
    wisdom: 0,
    charisma: 2,
  },
  Hynne: {
    strength: -2,
    dexterity: 2,
    constitution: 0,
    intelligence: 0,
    wisdom: 1,
    charisma: 0,
  },
  Qareen: {
    strength: -1,
    dexterity: 0,
    constitution: 0,
    intelligence: 0,
    wisdom: 0,
    charisma: 2,
  },
  Minauro: {
    strength: 2,
    dexterity: 0,
    constitution: 2,
    intelligence: -2,
    wisdom: -1,
    charisma: -1,
  },
  Kliren: {
    strength: 0,
    dexterity: 1,
    constitution: -1,
    intelligence: 2,
    wisdom: 0,
    charisma: 0,
  },
  Medusa: {
    strength: 0,
    dexterity: 0,
    constitution: 0,
    intelligence: 0,
    wisdom: 2,
    charisma: 0,
  },
  Sílfide: {
    strength: -2,
    dexterity: 2,
    constitution: -1,
    intelligence: 0,
    wisdom: 1,
    charisma: 0,
  },
  Tritão: {
    strength: 0,
    dexterity: 0,
    constitution: 1,
    intelligence: 0,
    wisdom: 1,
    charisma: 0,
  },
};

export const CLASS_MODIFIERS: Record<string, Record<string, number>> = {
  Arcanista: {
    strength: -2,
    dexterity: 1,
    constitution: -1,
    intelligence: 3,
    wisdom: 2,
    charisma: 0,
  },
  Bárbaro: {
    strength: 3,
    dexterity: 2,
    constitution: 2,
    intelligence: -1,
    wisdom: 0,
    charisma: 0,
  },
  Druida: {
    strength: 0,
    dexterity: 1,
    constitution: 2,
    intelligence: 1,
    wisdom: 2,
    charisma: 0,
  },
  Bucaneiro: {
    strength: 2,
    dexterity: 2,
    constitution: 1,
    intelligence: 0,
    wisdom: 0,
    charisma: 1,
  },
  Caçador: {
    strength: 1,
    dexterity: 3,
    constitution: 1,
    intelligence: 0,
    wisdom: 2,
    charisma: 0,
  },
  Cavaleiro: {
    strength: 2,
    dexterity: 0,
    constitution: 3,
    intelligence: 1,
    wisdom: 0,
    charisma: 1,
  },
  Clérigo: {
    strength: 0,
    dexterity: 0,
    constitution: 1,
    intelligence: 1,
    wisdom: 3,
    charisma: 1,
  },
  Guerreiro: {
    strength: 3,
    dexterity: 1,
    constitution: 2,
    intelligence: 0,
    wisdom: 0,
    charisma: 0,
  },
  Inventor: {
    strength: -1,
    dexterity: 1,
    constitution: 1,
    intelligence: 3,
    wisdom: 1,
    charisma: -1,
  },
  Ladino: {
    strength: 0,
    dexterity: 3,
    constitution: 1,
    intelligence: 2,
    wisdom: 0,
    charisma: 1,
  },
  Lutador: {
    strength: 3,
    dexterity: 2,
    constitution: 2,
    intelligence: -1,
    wisdom: 0,
    charisma: -1,
  },
  Nobre: {
    strength: 1,
    dexterity: 1,
    constitution: 0,
    intelligence: 1,
    wisdom: 0,
    charisma: 3,
  },
  Paladino: {
    strength: 2,
    dexterity: 0,
    constitution: 1,
    intelligence: 0,
    wisdom: 2,
    charisma: 2,
  },
  Ranger: {
    strength: 1,
    dexterity: 2,
    constitution: 1,
    intelligence: 1,
    wisdom: 2,
    charisma: 0,
  },
  Samurai: {
    strength: 3,
    dexterity: 2,
    constitution: 1,
    intelligence: 0,
    wisdom: 0,
    charisma: 0,
  },
  Templário: {
    strength: 2,
    dexterity: 0,
    constitution: 2,
    intelligence: 0,
    wisdom: 2,
    charisma: 1,
  },
  InventorArcano: {
    strength: -1,
    dexterity: 0,
    constitution: 1,
    intelligence: 4,
    wisdom: 1,
    charisma: -1,
  },
};
